### ISSUE TITLE
mira poppy's event crashes the player when they get killed without a source

### ISSUE THREAD

**Issue by kuba26038** [textstack/band_of_gigantism#12]
**Describe the bug**
game crashes when i equip the mark of the obliterated

**To Reproduce**
step one- equip the mark
step two- die
step three- cover yourself in oil
step four- crash

**Expected behavior**
i have no clue man, i just got this mod to work, give me a break

**Screenshots**

**Versions (Important! Please do this):**
 - Minecraft version: 1.18.2
 - Forge version: 40.0.20
 - Mod version: band_of_gigantism-1.18.2-1.1.0

**Additional context**
the crash: 

[crash-2022-05-18_18.13.25-server.txt](https://github.com/textstack/band_of_gigantism/files/8718096/crash-2022-05-18_18.13.25-server.txt)

**Comment by textstack** [comment]
Fix is on CurseForge, it'll take a few minutes to process before going public.
