### ISSUE TITLE
Config option to prevent the size of held items from scaling inversely to player size

### ISSUE THREAD

**Issue by NyanMC** [textstack/band_of_gigantism#15]
**Is your feature request related to a problem? Please describe.**

When at a size of 0.5 or less, it becomes basically impossible to hold items such as shields as they obstruct huge amounts of the screen and effectively make themselves impossible to use. This is especially notable when using the Mask of Diminishment or Band of Apathy, where items such as shields literally take up your entire screen.

**Describe the solution you'd like**
This could easily be solved by having a config option which makes it so that the player's held items do not scale inversely of their size. This would make the size of the held items in the first-person view equivalent to how they would look like at normal size, at the cost of some immersion breaking.

**Describe alternatives you've considered**
One thing that I could do is use a resource pack to turn items such as shields invisible when held. This could work, however there are a lot of items that I would need to change and it would be a lot more time consuming to do that.

**Additional context**
![image](https://user-images.githubusercontent.com/44331238/223899187-bb3aab0a-762d-4840-8652-2d7946ef83eb.png)
How a shield looks in the first person view with a band of apathy equipped. You can't tell me this isn't ridiculous.

**Comment by textstack** [comment]
I'm not ignoring this, I'm just a tad busy. I'm thinking about making a scale factor setting for how strongly player size affects hand size and possibly also pushing shields down as you scale down.

**Comment by textstack** [comment]
got it
