### ISSUE TITLE
Totem of Undying does not allow equipping Mark of the Obliterated

### ISSUE THREAD

**Issue by Jackiecrazy** [textstack/band_of_gigantism#16]
**Describe the bug**
Totem of Undying does not protect against damage that bypasses invulnerability, unlike what the Github wiki seems to suggest. This is built into vanilla because the totem does not and should not break from falling into the void. I think false hand is the only way to negate the damage.

**To Reproduce**
1. Hold totem of undying
2. Equip Mark of the Obliterated

**Expected behavior**
Either the totem should work, or the wiki should be updated to note that it doesn't.

**Screenshots**

**Versions (Important! Please do this):**
 - Minecraft version: 1.19.2
 - Forge version: 43.2.8
 - Mod version: 1.1.3

**Comment by textstack** [comment]
got it
